### ISSUE TITLE
[RFC] My thoughts for this repo

### ISSUE THREAD

**Issue by CodeDoes** [jyapayne/nim-extensions#2]
I want to eliminate the boilerplate code for oop in nim

at the moment I do something like this, which is way too much typing and hassle

```nim
type
  Object = ref object
    s: string
    i: int
    b: bool
proc init(self:Object,s:string,i:int,b:bool)=
  self.s=s
  self.i=i
  self.b=b
proc newObject(s:string,i:int,b:bool):Object=
  system.new result
  result.init(s,i,b)
```
As you can see this is way too much typing. 
unfortunately the class macro isn't perfect either.
I'm thinking that the new macro you've made should be the place to concentrate on when bring oop into nim.

**Comment by bluenote10** [comment]
What is the status of your fork https://github.com/CodeDoes/nim-extensions (commenting here since commenting is disabled on the fork)? Does it make sense to merge it back?

**Comment by jyapayne** [comment]
Closing this since I merged the PR that he made quite some time ago. It was made when this repo was still only the OOP macro.
